# Generated by Django 5.1.7 on 2025-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imposto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
